name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
    
      run: go build -v ./...

    - name: Test
      run: go test -v ./test/server_test.go

  Publish_image:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Enviroment Variables
        run: |
          echo "COMMIT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_NAME=$(basename ${GITHUB_REPOSITORY})" >> $GITHUB_ENV
      - name: Deploy to Docker Registry
        run: |
          
          docker build . --file Dockerfile --tag ${DOCKER_IMAGE_NAME}
          docker tag ${DOCKER_IMAGE_NAME}:latest ${{secrets.DOCKER_USER}}/${DOCKER_IMAGE_NAME}:${COMMIT}
          docker push ${{secrets.DOCKER_USER}}/${DOCKER_IMAGE_NAME}:${COMMIT}
